language: ruby
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "rbx-2"
  - "jruby-1.7.5"
before_script:
  - psql -c 'create database "que-test"' -U postgres
  - bundle exec ruby -r sequel -r ./lib/que -e 'Que.connection=Sequel.connect("postgres://localhost/que-test"); Que.migrate!'

script: "./spec/travis.rb"

addons:
  postgresql: 9.3
